# Generated by Django 5.1.3 on 2024-12-20 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_remove_follower_followee_remove_follower_follower_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
